from graph import *

x=graph()
x.addVertex(10)
x.addEdge(0,1,False,1)
x.addEdge(0,2,False,1)
x.addEdge(0,3,False,1)
x.addEdge(1,2,False,1)
x.addEdge(2,1,False,1)
x.addEdge(3,5,False,1)
x.addEdge(5,3,False,1)
x.addEdge(5,2,False,1)
x.addEdge(3,2,False,1)
x.addEdge(1,5,False,3)
x.addEdge(5,1,False,0)
x.addEdge(4,6,False,1)
x.addEdge(6,4,False,1)
x.addEdge(8,9,False,7)

print (x.store)
print ("Depth")
print (x.traverse(0,False))
print ("Breadth")
print (x.traverse(1,True))
print ("Breadth; start=None")
print (x.traverse(None,True))
print(x.connectivity(6,0))
print(x.path(6,0))
