from tree import *
from binary_tree import *

a = tree("A")
b = tree("B")
c = tree("C")
d = tree("D")
e = tree("E")
f = tree("F")
g = tree("G")
h = tree("H")
i = tree("I")
g.AddSuccessor(i)
d.AddSuccessor(g)
d.AddSuccessor(h)
b.AddSuccessor(e)
b.AddSuccessor(f)
a.AddSuccessor(b)
a.AddSuccessor(c)
a.AddSuccessor(d)
a.Print_DepthFirst()
a.Get_LevelOrder()
rval = a.ConvertToBinaryTree()
print(type(rval))
rval.Print_tree("")
